# A+++++ Prometheus Configuration
# Comprehensive monitoring for CounselFlow A+++++ architecture

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'counselflow-a++++'
    environment: 'production'

# Rules for A+++++ architecture alerts
rule_files:
  - "rules/*.yml"

# A+++++ Service Discovery and Scraping
scrape_configs:
  # CounselFlow API Metrics
  - job_name: 'counselflow-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/api/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    honor_labels: true
    
  # CounselFlow Web Application Metrics
  - job_name: 'counselflow-web'
    static_configs:
      - targets: ['web:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    
  # Nginx Metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 15s
    
  # PostgreSQL Database Metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s
    
  # Redis Metrics
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    
  # Node Exporter for System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    
  # cAdvisor for Container Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: '/metrics'
    
  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

# A+++++ Alerting Configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Remote write for long-term storage (optional)
# remote_write:
#   - url: "https://your-remote-prometheus-endpoint/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"